{{- if (include "acapy.api.createSecret" .) -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.api.secret.name" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwt: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "jwt" "Length" 32) }}
  webhookapi: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "webhookapi" "Length" 32) }}
  {{- if .Values.acapy.secret.adminApiKey.generated }}
  adminApiKey: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.api.secret.name" .) "Key" "adminApiKey" "Length" 32) }}
  {{ else }}
  adminApiKey: {{ include "common.secrets.lookup" (dict "secret" (include "acapy.api.secret.name" .) "key" "adminApiKey" "defaultValue" .Values.acapy.secret.adminApiKey.value "context" $) }}
  {{- end }}
{{- end -}}
