{{- if (include "acapy.database.createSecret" .) -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.database.secret.name" . }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-password: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.database.secret.name" .) "Key" (include "acapy.database.adminPasswordKey" .)) }}
  database-user: {{ .Values.acapy.walletStorageCredentials.account | b64enc }}
  database-password: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.database.secret.name" .) "Key" (include "acapy.database.userPasswordKey" .)) }}
{{- end -}}
