{{- if (include "acapy.walletKey.createSecret" .) -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.walletkey.secret.name" . }}
  labels:
    {{- include "acapy.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  walletKey: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "acapy.walletkey.secret.name" .) "Key" "walletKey" "Length" 32) }}
{{- end -}}
