version: "3.9"
services:
  verifier:
    build:
      context: ../services/verifier
      dockerfile: Dockerfile
    depends_on:
      - traction-agent
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${VERIFIER_PSQL_DB}
      - POSTGRESQL_USER=${VERIFIER_PSQL_USER}
      - POSTGRESQL_PASSWORD=${VERIFIER_PSQL_PASS}
    ports:
      - ${VERIFIER_SERVICE_PORT}:5000
    extra_hosts:
     - host.docker.internal:host-gateway
    volumes:
     - ../services/verifier:/app:rw
  holder:
    build:
      context: ../services/holder
      dockerfile: Dockerfile
    depends_on:
      - traction-agent
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}      
      - POSTGRESQL_DB=${HOLDER_PSQL_DB}
      - POSTGRESQL_USER=${HOLDER_PSQL_USER}
      - POSTGRESQL_PASSWORD=${HOLDER_PSQL_PASS}
    ports:
      - ${HOLDER_SERVICE_PORT}:5000
    extra_hosts:
     - host.docker.internal:host-gateway
    volumes:
    - ../services/holder:/app:rw
  traction-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.2
    depends_on:
      - traction-db
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5;
        aca-py start \
        --auto-provision
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_HTTP_PORT} \
        --webhook-url http://verifier:5000/log \
        --webhook-url http://holder:5000/log \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --wallet-name traction-wallet  \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --label '${AGENT_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \       
        ${ACAPY_TAILS_UPLOAD_URL} \   
        "
    ]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
    extra_hosts:
     - host.docker.internal:host-gateway
  traction-db:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
volumes:
  traction-wallet: