apiVersion: v1
kind: Service
metadata:
  name: {{ include "holder.fullname" . }}
  labels:
    {{- include "holder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.holder.service.type }}
  ports:
    - port: {{ .Values.holder.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "holder.selectorLabels" . | nindent 4 }}