name: Build Traction Service
description: Build a Traction Service
inputs:
  context:
    required: true
    type: string
  image_name:
    required: true
    type: string
  registry:
    required: true
    type: string
    default: ghcr.io
  registry_username:
    required: true
    type: string
  registry_password:
    required: true

outputs:
  image_tag:
    description: "Image Tag"
    value: ${{ steps.values.outputs.image_tag }}
  image_version:
    description: "Image Version"
    value: ${{ steps.values.outputs.image_version }}
  buildtime:
    description: "Build Time"
    value: ${{ steps.values.outputs.buildtime }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2      
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      shell: bash      
      run: |
        cd ${{ inputs.context }}
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      shell: bash  
      run: |
        cd ${{ inputs.context }}
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      shell: bash  
      run: |
        cd ${{ inputs.context }}
        pytest tests
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry}}
        username: ${{ inputs.registry_username}}
        password: ${{ inputs.registry_password }}

    - name: Prepare docker tags for image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: type=sha

    - name: Build and push image
      id: builder
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - id: values  
      shell: bash
      run: |
        echo "::set-output name=image_tag::${{ fromJSON(steps.meta.outputs.json).tags[0] }}"
        echo "::set-output name=image_version::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
        echo "::set-output name=buildtime::${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}"
