{{- if .Values.ingress.enabled -}}
{{- $acapyFullName := include "acapy.fullname" . -}}
{{- $tenantProxyFullName := include "tenant_proxy.fullname" . -}}
{{- $uiFullName := include "tenant-ui.fullname" . -}}
{{- $uiHttpPort := .Values.ui.service.httpPort -}}
{{- $httpPort := .Values.acapy.service.httpPort -}}
{{- $adminPort := .Values.acapy.service.adminPort -}}
{{- $tenantProxyPort := .Values.tenant_proxy.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "global.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ include "acapy.host" . | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $acapyFullName }}
                port:
                  number: {{ $httpPort }}
              {{- else }}
              serviceName: {{ $acapyFullName }}
              servicePort: {{ $httpPort }}
              {{- end }}
    - host: {{ include "acapy.admin.host" . | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $acapyFullName }}
                port:
                  number: {{ $adminPort }}
              {{- else }}
              serviceName: {{ $acapyFullName }}
              servicePort: {{ $adminPort }}
              {{- end }}
    - host: {{ include "tenant_proxy.host" . | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $tenantProxyFullName }}
                port:
                  number: {{ $tenantProxyPort }}
              {{- else }}
              serviceName: {{ $tenantProxyFullName }}
              servicePort: {{ $tenantProxyPort }}
              {{- end }}
    {{- if .Values.ui.enabled }}
    - host: {{ include "tenant-ui.host" . | quote }}
      http:
        paths:
          - path: /
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $uiFullName }}
                port:
                  number: {{ $uiHttpPort }}
              {{- else }}
              serviceName: {{ $uiFullName }}
              servicePort: {{ $uiHttpPort }}
              {{- end }}
    {{- end }}
{{- end }}
