{{- if .Values.ingress.enabled -}}
{{- $acapyFullName := include "traction.acapy.fullname" . -}}
{{- $tenantProxyFullName := include "tenant_proxy.fullname" . -}}
{{- $uiFullName := include "tenant-ui.fullname" . -}}
{{- $uiHttpPort := .Values.ui.service.httpPort -}}
{{- $httpPort := .Values.acapy.service.ports.http -}}
{{- $adminPort := .Values.acapy.service.ports.admin -}}
{{- $tenantProxyPort := .Values.tenant_proxy.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "global.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ include "tenant_proxy.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $tenantProxyFullName }}
                port:
                  number: {{ $tenantProxyPort }}
    {{- if .Values.ui.enabled }}
    - host: {{ include "tenant-ui.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $uiFullName }}
                port:
                  number: {{ $uiHttpPort }}
    {{- end }}
{{- end }}
