apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traction.acapy.plugin.innkeeper.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  tenantid: {{ include "getOrGenerateUUID" (dict "Name" (include "traction.acapy.plugin.innkeeper.name" .) "Key" "tenantid" "Namespace" .Release.Namespace "Kind" "Secret") }}
  walletkey: {{ include "getOrGeneratePass" (dict "Length" 32 "Name" (include "traction.acapy.plugin.innkeeper.name" .) "Key" "walletkey" "Namespace" .Release.Namespace "Kind" "Secret") }}
