apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "postgresql.secret.name" . }}
  labels:
    {{- include "common.selectorLabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgresql-password: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "postgresql.secret.name" .) "Key" "postgresql-password") }}
  database-user: cG9zdGdyZXM=
  database-password: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (include "postgresql.secret.name" .) "Key" "postgresql-password") }}
