{{- if .Values.tenant_proxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tenant_proxy.fullname" . }}
  labels:
    {{- include "tenant_proxy.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tenant_proxy.fullname" . }}
  minReplicas: {{ .Values.tenant_proxy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.tenant_proxy.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.tenant_proxy.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.tenant_proxy.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.tenant_proxy.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.tenant_proxy.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.tenant_proxy.autoscaling.stabilizationWindowSeconds }}
{{- end }}
