# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.attach_decorator_data_jws_header import (
    AttachDecoratorDataJWSHeader,
)


class AttachDecoratorData1JWS(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttachDecoratorData1JWS - a model defined in OpenAPI

        header: The header of this AttachDecoratorData1JWS.
        protected: The protected of this AttachDecoratorData1JWS [Optional].
        signature: The signature of this AttachDecoratorData1JWS.
    """

    header: AttachDecoratorDataJWSHeader
    protected: Optional[str] = None
    signature: str

    @validator("protected")
    def protected_pattern(cls, value):
        assert value is not None and re.match(r"^[-_a-zA-Z0-9]*$", value)
        return value

    @validator("signature")
    def signature_pattern(cls, value):
        assert value is not None and re.match(r"^[-_a-zA-Z0-9]*$", value)
        return value


AttachDecoratorData1JWS.update_forward_refs()
