# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class AttachDecoratorDataJWSHeader(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttachDecoratorDataJWSHeader - a model defined in OpenAPI

        kid: The kid of this AttachDecoratorDataJWSHeader.
    """

    kid: str

    @validator("kid")
    def kid_pattern(cls, value):
        assert value is not None and re.match(
            r"^did:(?:key:z[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]+|sov:[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}(;.*)?(\?.*)?#.+)$",
            value,
        )
        return value


AttachDecoratorDataJWSHeader.update_forward_refs()
