# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.indy_cred_info import IndyCredInfo


class CredInfoList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CredInfoList - a model defined in OpenAPI

        results: The results of this CredInfoList [Optional].
    """

    results: Optional[List[IndyCredInfo]] = None


CredInfoList.update_forward_refs()
