# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.input_descriptors import InputDescriptors


class DIFProofProposal(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFProofProposal - a model defined in OpenAPI

        input_descriptors: The input_descriptors of this DIFProofProposal [Optional].
    """

    input_descriptors: Optional[List[InputDescriptors]] = None


DIFProofProposal.update_forward_refs()
