# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class DIFHolder(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFHolder - a model defined in OpenAPI

        directive: The directive of this DIFHolder [Optional].
        field_id: The field_id of this DIFHolder [Optional].
    """

    directive: Optional[str] = None
    field_id: Optional[List[str]] = None


DIFHolder.update_forward_refs()
