# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class EndorserInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndorserInfo - a model defined in OpenAPI

        endorser_did: The endorser_did of this EndorserInfo.
        endorser_name: The endorser_name of this EndorserInfo [Optional].
    """

    endorser_did: str
    endorser_name: Optional[str] = None


EndorserInfo.update_forward_refs()
