# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class GetDIDVerkeyResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GetDIDVerkeyResponse - a model defined in OpenAPI

        verkey: The verkey of this GetDIDVerkeyResponse [Optional].
    """

    verkey: Optional[str] = None

    @validator("verkey")
    def verkey_pattern(cls, value):
        assert value is not None and re.match(
            r"^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{43,44}$",
            value,
        )
        return value


GetDIDVerkeyResponse.update_forward_refs()
