# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.indy_eq_proof import IndyEQProof
from acapy_wrapper.models.indy_ge_proof import IndyGEProof


class IndyPrimaryProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyPrimaryProof - a model defined in OpenAPI

        eq_proof: The eq_proof of this IndyPrimaryProof [Optional].
        ge_proofs: The ge_proofs of this IndyPrimaryProof [Optional].
    """

    eq_proof: Optional[IndyEQProof] = None
    ge_proofs: Optional[List[IndyGEProof]] = None


IndyPrimaryProof.update_forward_refs()
