# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.indy_proof_req_attr_spec_non_revoked import (
    IndyProofReqAttrSpecNonRevoked,
)


class IndyProofReqAttrSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofReqAttrSpec - a model defined in OpenAPI

        name: The name of this IndyProofReqAttrSpec [Optional].
        names: The names of this IndyProofReqAttrSpec [Optional].
        non_revoked: The non_revoked of this IndyProofReqAttrSpec [Optional].
        restrictions: The restrictions of this IndyProofReqAttrSpec [Optional].
    """

    name: Optional[str] = None
    names: Optional[List[str]] = None
    non_revoked: Optional[IndyProofReqAttrSpecNonRevoked] = None
    restrictions: Optional[List[Dict[str, str]]] = None


IndyProofReqAttrSpec.update_forward_refs()
