# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class IndyPresAttrSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyPresAttrSpec - a model defined in OpenAPI

        cred_def_id: The cred_def_id of this IndyPresAttrSpec [Optional].
        mime_type: The mime_type of this IndyPresAttrSpec [Optional].
        name: The name of this IndyPresAttrSpec.
        referent: The referent of this IndyPresAttrSpec [Optional].
        value: The value of this IndyPresAttrSpec [Optional].
    """

    cred_def_id: Optional[str] = None
    mime_type: Optional[str] = None
    name: str
    referent: Optional[str] = None
    value: Optional[str] = None

    @validator("cred_def_id")
    def cred_def_id_pattern(cls, value):
        assert value is not None and re.match(
            r"^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):3:CL:(([1-9][0-9]*)|([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}:2:.+:[0-9.]+)):(.+)?$",
            value,
        )
        return value


IndyPresAttrSpec.update_forward_refs()
