# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class KeylistQueryPaginate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    KeylistQueryPaginate - a model defined in OpenAPI

        limit: The limit of this KeylistQueryPaginate [Optional].
        offset: The offset of this KeylistQueryPaginate [Optional].
    """

    limit: Optional[int] = None
    offset: Optional[int] = None


KeylistQueryPaginate.update_forward_refs()
