# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.credential import Credential
from acapy_wrapper.models.ld_proof_vc_detail_options import LDProofVCDetailOptions


class LDProofVCDetail(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LDProofVCDetail - a model defined in OpenAPI

        credential: The credential of this LDProofVCDetail.
        options: The options of this LDProofVCDetail.
    """

    credential: Credential
    options: LDProofVCDetailOptions


LDProofVCDetail.update_forward_refs()
