# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class PerformRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PerformRequest - a model defined in OpenAPI

        name: The name of this PerformRequest [Optional].
        params: The params of this PerformRequest [Optional].
    """

    name: Optional[str] = None
    params: Optional[Dict[str, str]] = None


PerformRequest.update_forward_refs()
