# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class RevRegsCreated(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RevRegsCreated - a model defined in OpenAPI

        rev_reg_ids: The rev_reg_ids of this RevRegsCreated [Optional].
    """

    rev_reg_ids: Optional[List[str]] = None


RevRegsCreated.update_forward_refs()
