# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.credential_preview import CredentialPreview


class V10CredentialConnFreeOfferRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V10CredentialConnFreeOfferRequest - a model defined in OpenAPI

        auto_issue: The auto_issue of this V10CredentialConnFreeOfferRequest [Optional].
        auto_remove: The auto_remove of this V10CredentialConnFreeOfferRequest [Optional].
        comment: The comment of this V10CredentialConnFreeOfferRequest [Optional].
        cred_def_id: The cred_def_id of this V10CredentialConnFreeOfferRequest.
        credential_preview: The credential_preview of this V10CredentialConnFreeOfferRequest.
        trace: The trace of this V10CredentialConnFreeOfferRequest [Optional].
    """

    auto_issue: Optional[bool] = None
    auto_remove: Optional[bool] = None
    comment: Optional[str] = None
    cred_def_id: str
    credential_preview: CredentialPreview
    trace: Optional[bool] = None

    @validator("cred_def_id")
    def cred_def_id_pattern(cls, value):
        assert value is not None and re.match(
            r"^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):3:CL:(([1-9][0-9]*)|([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}:2:.+:[0-9.]+)):(.+)?$",
            value,
        )
        return value


V10CredentialConnFreeOfferRequest.update_forward_refs()
