# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.v20_pres_ex_record import V20PresExRecord


class V20PresExRecordList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresExRecordList - a model defined in OpenAPI

        results: The results of this V20PresExRecordList [Optional].
    """

    results: Optional[List[V20PresExRecord]] = None


V20PresExRecordList.update_forward_refs()
