# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.dif_pres_spec import DIFPresSpec
from acapy_wrapper.models.indy_pres_spec import IndyPresSpec


class V20PresSpecByFormatRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresSpecByFormatRequest - a model defined in OpenAPI

        dif: The dif of this V20PresSpecByFormatRequest [Optional].
        indy: The indy of this V20PresSpecByFormatRequest [Optional].
        trace: The trace of this V20PresSpecByFormatRequest [Optional].
    """

    dif: Optional[DIFPresSpec] = None
    indy: Optional[IndyPresSpec] = None
    trace: Optional[bool] = None


V20PresSpecByFormatRequest.update_forward_refs()
