# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.attach_decorator import AttachDecorator
from acapy_wrapper.models.v20_cred_format import V20CredFormat
from acapy_wrapper.models.v20_cred_preview import V20CredPreview


class V20CredOffer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredOffer - a model defined in OpenAPI

        id: The id of this V20CredOffer [Optional].
        type: The type of this V20CredOffer [Optional].
        comment: The comment of this V20CredOffer [Optional].
        credential_preview: The credential_preview of this V20CredOffer [Optional].
        formats: The formats of this V20CredOffer.
        offersattach: The offersattach of this V20CredOffer.
        replacement_id: The replacement_id of this V20CredOffer [Optional].
    """

    id: Optional[str] = None
    type: Optional[str] = None
    comment: Optional[str] = None
    credential_preview: Optional[V20CredPreview] = None
    formats: List[V20CredFormat]
    offersattach: List[AttachDecorator]
    replacement_id: Optional[str] = None


V20CredOffer.update_forward_refs()
