# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.dif_proof_request import DIFProofRequest
from acapy_wrapper.models.indy_proof_request import IndyProofRequest


class V20PresRequestByFormat(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresRequestByFormat - a model defined in OpenAPI

        dif: The dif of this V20PresRequestByFormat [Optional].
        indy: The indy of this V20PresRequestByFormat [Optional].
    """

    dif: Optional[DIFProofRequest] = None
    indy: Optional[IndyProofRequest] = None


V20PresRequestByFormat.update_forward_refs()
