# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.ld_proof_vc_detail import LDProofVCDetail


class V20CredFilterLDProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredFilterLDProof - a model defined in OpenAPI

        ld_proof: The ld_proof of this V20CredFilterLDProof.
    """

    ld_proof: LDProofVCDetail


V20CredFilterLDProof.update_forward_refs()
