# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class V20CredRequestRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredRequestRequest - a model defined in OpenAPI

        holder_did: The holder_did of this V20CredRequestRequest [Optional].
    """

    holder_did: Optional[str] = None


V20CredRequestRequest.update_forward_refs()
