# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.v20_cred_filter import V20CredFilter
from acapy_wrapper.models.v20_cred_preview import V20CredPreview


class V20CredOfferConnFreeRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredOfferConnFreeRequest - a model defined in OpenAPI

        auto_issue: The auto_issue of this V20CredOfferConnFreeRequest [Optional].
        auto_remove: The auto_remove of this V20CredOfferConnFreeRequest [Optional].
        comment: The comment of this V20CredOfferConnFreeRequest [Optional].
        credential_preview: The credential_preview of this V20CredOfferConnFreeRequest [Optional].
        filter: The filter of this V20CredOfferConnFreeRequest.
        trace: The trace of this V20CredOfferConnFreeRequest [Optional].
    """

    auto_issue: Optional[bool] = None
    auto_remove: Optional[bool] = None
    comment: Optional[str] = None
    credential_preview: Optional[V20CredPreview] = None
    filter: V20CredFilter
    trace: Optional[bool] = None


V20CredOfferConnFreeRequest.update_forward_refs()
