# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from acapy_wrapper.models.v20_cred_filter_ld_proof import V20CredFilterLDProof


class V20CredRequestFree(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredRequestFree - a model defined in OpenAPI

        auto_remove: The auto_remove of this V20CredRequestFree [Optional].
        comment: The comment of this V20CredRequestFree [Optional].
        connection_id: The connection_id of this V20CredRequestFree.
        filter: The filter of this V20CredRequestFree.
        holder_did: The holder_did of this V20CredRequestFree [Optional].
        trace: The trace of this V20CredRequestFree [Optional].
    """

    auto_remove: Optional[bool] = None
    comment: Optional[str] = None
    connection_id: str
    filter: V20CredFilterLDProof
    holder_did: Optional[str] = None
    trace: Optional[bool] = None


V20CredRequestFree.update_forward_refs()
