# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class V20CredFormat(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredFormat - a model defined in OpenAPI

        attach_id: The attach_id of this V20CredFormat.
        format: The format of this V20CredFormat.
    """

    attach_id: str
    format: str


V20CredFormat.update_forward_refs()
