name: Update Manifests
description: Update Manifest Repository
inputs:
  repository_key:
    required: true
    type: string
  repository:
    required: true
    type: string
  repository_checkout_path:
    required: true
    type: string
    default: manifests-repo
  charts_path:
    required: true
    type: string
    default: charts/traction
  target:
    required: true
    type: string
    default: 'dev'
  release_version:
    required: false
    type: string
  api_image_tag:
    required: false
    type: string
  api_image_version:
    required: false
    type: string
  api_image_buildtime:
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ./scripts
        cp .env-example .env
        docker-compose -f "docker-compose.yml" up -d --build
      shell: bash
