name: Update Manifests
description: Update Manifest Repository
inputs:
  repository_key:
    required: true
    type: string
  repository:
    required: true
    type: string
  repository_checkout_path:
    required: true
    type: string
    default: manifests-repo
  charts_path:
    required: true
    type: string
    default: charts/traction
  target:
    required: true
    type: string
    default: 'dev'
  release_version:
    required: false
    type: string
  api_image_tag:
    required: false
    type: string
  api_image_version:
    required: false
    type: string
  api_image_buildtime:
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Start containers
      run: |
        cd ./scripts
        cp .env-example .env
        . /dev/stdin <<<"$(cat <(curl -s --raw https://raw.githubusercontent.com/bcgov/DITP-DevOps/main/code/snippets/getDockerHost))" 
        export DOCKERHOST=$(getDockerHost)
        echo $DOCKERHOST
        export TRACTION_ENDPOINT=http://$DOCKERHOST:5100
        echo $TRACTION_ENDPOINT
        export ENDORSER_ENDPOINT=http://$DOCKERHOST:5300
        export ACAPY_ENDORSER_ENDPOINT=http://$DOCKERHOST:9030
        export ACAPY_ENDPOINT=http://$DOCKERHOST:8030
        export ACAPY_ADMIN_URL=http://$DOCKERHOST:8031
        export TRACTION_HOST_URL=http://$DOCKERHOST:5000
        docker-compose -f "docker-compose.yml" up -d --build
      shell: bash

    - name: Display running
      run: |
        cd ./scripts
        docker ps
      shell: bash

    - name: Run pytest
      run: |
        cd ./scripts
        docker exec scripts_traction-api_1 pytest -k 'test_check_in' --log-level=debug --asyncio-mode=strict
      shell: bash
