{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tenant-ui.fullname" . }}
  labels:
    {{- include "tenant-ui.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/ui/configmap.yaml") . | sha256sum }}
    checksum/innkeeper-secret: {{ include (print $.Template.BasePath "/acapy/plugin_innkeeper_secret.yaml") . | sha256sum }}
spec:
  {{- if not .Values.ui.autoscaling.enabled }}
  replicas: {{ .Values.ui.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tenant-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tenant-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ui.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tenant-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: tenant-ui
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.httpPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: SERVER_INNKEEPER_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "acapy.plugin.innkeeper.name" . }}
                  key: tenantid
            - name: SERVER_INNKEEPER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "acapy.plugin.innkeeper.name" . }}
                  key: walletkey
          envFrom:
            - configMapRef:
                name: {{ template "tenant-ui.fullname" . }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          volumeMounts:
            - name: reservation-form
              mountPath: "/usr/src/app/frontend/dist/forms/reservation.json"
              subPath: "reservation.json"
              readOnly: true
      volumes:
        - name: reservation-form
          configMap:
            name: {{ include "tenant-ui.fullname" . }}-form
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
