{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenant-ui.fullname" . }}-form
  labels:
    {{- include "tenant-ui.labels" . | nindent 4 }}
data:
  reservation.json: |
    {{ quote .Values.ui.oidc.reservationForm | nindent 4 }}
{{- end -}}