global:
  ingressSuffix: -test.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:0.2.13"
    version: "0.2.13"
    buildtime: "2022-10-28T01:30:31.105Z"
    pullPolicy: Always
  tails:
    enabled: true
tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:0.2.13"
    version: "0.2.13"
    buildtime: "2022-01-28T18:19:10.574Z"
    pullPolicy: Always
