"""add contact_id to issuecredential

Revision ID: e40469d1045a
Revises: 12a486c50ac3
Create Date: 2022-05-09 16:19:46.906138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision = "e40469d1045a"
down_revision = "12a486c50ac3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issuecredential", sa.Column("contact_id", pg.UUID(as_uuid=True)))

    op.create_foreign_key(
        "issuecredential_contact_contact_id",
        "issuecredential",
        "contact",
        ["contact_id"],
        ["contact_id"],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issuecredential", "contact_id")
    op.drop_constraint("issuecredential_contact_contact_id")
    # ### end Alembic commands ###
