"""issue credential

Revision ID: e065bba5d8cd
Revises: f9978dd2ced8
Create Date: 2022-02-25 00:10:22.000481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision = "e065bba5d8cd"
down_revision = "f9978dd2ced8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuecredential",
        sa.Column(
            "id",
            pg.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("wallet_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("connection_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("cred_type", sa.String(), nullable=False),
        sa.Column("cred_protocol", sa.String(), nullable=False),
        sa.Column("schema_id", sa.String(), nullable=True),
        sa.Column("cred_def_id", sa.String(), nullable=True),
        sa.Column("credential", sa.String(), nullable=False),
        sa.Column("issue_state", sa.String(), nullable=False),
        sa.Column("workflow_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("cred_exch_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at",
            pg.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            pg.TIMESTAMP(),
            server_default=sa.text("now()"),
            onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issuecredential")
    # ### end Alembic commands ###
