"""tenant-single-table-inheritance

Revision ID: 9a79e062eb65
Revises: 5f13cfb97471
Create Date: 2022-07-26 16:19:06.043858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a79e062eb65'
down_revision = '5f13cfb97471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant2',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wallet_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wallet_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tenant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index(op.f('ix_tenant2_name'), 'tenant2', ['name'], unique=False)
    op.create_index(op.f('ix_tenant2_tenant_id'), 'tenant2', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant2_tenant_id'), table_name='tenant2')
    op.drop_index(op.f('ix_tenant2_name'), table_name='tenant2')
    op.drop_table('tenant2')
    # ### end Alembic commands ###
