"""v1-holder-presentation-add-columns

Revision ID: cd86ad6d3331
Revises: d4edfc38f49e
Create Date: 2022-07-15 13:06:44.154032

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "cd86ad6d3331"
down_revision = "d4edfc38f49e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "holder_presentation",
        sa.Column(
            "rejection_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "holder_presentation", sa.Column("presentation", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holder_presentation", "presentation")
    op.drop_column("holder_presentation", "rejection_comment")
    # ### end Alembic commands ###
