"""v1-message-table-fix

Revision ID: 3092e74e02a4
Revises: d0b54bf9b9a6
Create Date: 2022-06-17 13:49:37.002650

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3092e74e02a4"
down_revision = "d0b54bf9b9a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "revocation_comment")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message",
        sa.Column(
            "revocation_comment", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
