"""v1-tenant-configuration

Revision ID: 78d0d1c2b87a
Revises: d56ec2dae115
Create Date: 2022-06-16 11:38:57.239888

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78d0d1c2b87a"
down_revision = "d56ec2dae115"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_configuration",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("webhook_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("webhook_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("auto_respond_messages", sa.Boolean(), nullable=False),
        sa.Column(
            "auto_response_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("store_messages", sa.Boolean(), nullable=False),
        sa.Column("store_issuer_credentials", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_index(
        op.f("ix_tenant_configuration_tenant_id"),
        "tenant_configuration",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tenant_configuration_tenant_id"), table_name="tenant_configuration"
    )
    op.drop_table("tenant_configuration")
    # ### end Alembic commands ###
