"""v1_verifier_presentations

Revision ID: 7c527dcfae03
Revises: 3092e74e02a4
Create Date: 2022-06-21 20:07:21.353957

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c527dcfae03"
down_revision = "3092e74e02a4"
branch_labels = None
depends_on = None

create_verifier_presentation_request_timeline_func = """CREATE OR REPLACE FUNCTION verifier_presentation_request_timeline_func() RETURNS trigger AS $body$
    BEGIN
        IF NEW.status IS DISTINCT FROM OLD.status OR NEW.state IS DISTINCT FROM OLD.state THEN
            INSERT INTO "timeline" ( "item_id", "status", "state", "error_status_detail" )
            VALUES(NEW."verifier_presentation_id", NEW."status", NEW."state", NEW."error_status_detail");
            RETURN NEW;
        END IF;
        RETURN null;
    END;
    $body$ LANGUAGE plpgsql
"""  # noqa: E501

drop_verifier_presentation_request_timeline_func = (
    """DROP FUNCTION verifier_presentation_request_timeline_func"""
)

create_verifier_presentation_timeline_trigger = """CREATE TRIGGER verifier_presentation_timeline_trigger
AFTER INSERT OR UPDATE OF status, state ON verifier_presentation
FOR EACH ROW EXECUTE PROCEDURE verifier_presentation_request_timeline_func();"""

drop_verifier_presentation_timeline_trigger = (
    """DROP TRIGGER verifier_presentation_timeline_trigger ON verifier_presentation"""
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verifier_presentation",
        sa.Column(
            "verifier_presentation_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("contact_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "external_reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "error_status_detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("pres_exch_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "proof_request", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.contact_id"],
        ),
        sa.PrimaryKeyConstraint("verifier_presentation_id"),
    )
    # ### end Alembic commands ###
    op.execute(create_verifier_presentation_request_timeline_func)
    op.execute(create_verifier_presentation_request_timeline_func)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verifier_presentation_request")
    # ### end Alembic commands ###
    op.execute(create_verifier_presentation_timeline_trigger)
    op.execute(drop_verifier_presentation_timeline_trigger)
