# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ClaimFormat(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ClaimFormat - a model defined in OpenAPI

        jwt: The jwt of this ClaimFormat [Optional].
        jwt_vc: The jwt_vc of this ClaimFormat [Optional].
        jwt_vp: The jwt_vp of this ClaimFormat [Optional].
        ldp: The ldp of this ClaimFormat [Optional].
        ldp_vc: The ldp_vc of this ClaimFormat [Optional].
        ldp_vp: The ldp_vp of this ClaimFormat [Optional].
    """

    jwt: Optional[Dict[str, Any]] = Field(alias="jwt", default=None)
    jwt_vc: Optional[Dict[str, Any]] = Field(alias="jwt_vc", default=None)
    jwt_vp: Optional[Dict[str, Any]] = Field(alias="jwt_vp", default=None)
    ldp: Optional[Dict[str, Any]] = Field(alias="ldp", default=None)
    ldp_vc: Optional[Dict[str, Any]] = Field(alias="ldp_vc", default=None)
    ldp_vp: Optional[Dict[str, Any]] = Field(alias="ldp_vp", default=None)


ClaimFormat.update_forward_refs()
