# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.conn_record import ConnRecord


class ConnectionList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConnectionList - a model defined in OpenAPI

        results: The results of this ConnectionList [Optional].
    """

    results: Optional[List[ConnRecord]] = Field(alias="results", default=None)


ConnectionList.update_forward_refs()
