# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CreateWalletRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CreateWalletRequest - a model defined in OpenAPI

        image_url: The image_url of this CreateWalletRequest [Optional].
        key_management_mode: The key_management_mode of this CreateWalletRequest [Optional].
        label: The label of this CreateWalletRequest [Optional].
        wallet_dispatch_type: The wallet_dispatch_type of this CreateWalletRequest [Optional].
        wallet_key: The wallet_key of this CreateWalletRequest [Optional].
        wallet_key_derivation: The wallet_key_derivation of this CreateWalletRequest [Optional].
        wallet_name: The wallet_name of this CreateWalletRequest [Optional].
        wallet_type: The wallet_type of this CreateWalletRequest [Optional].
        wallet_webhook_urls: The wallet_webhook_urls of this CreateWalletRequest [Optional].
    """

    image_url: Optional[str] = Field(alias="image_url", default=None)
    key_management_mode: Optional[str] = Field(
        alias="key_management_mode", default=None
    )
    label: Optional[str] = Field(alias="label", default=None)
    wallet_dispatch_type: Optional[str] = Field(
        alias="wallet_dispatch_type", default=None
    )
    wallet_key: Optional[str] = Field(alias="wallet_key", default=None)
    wallet_key_derivation: Optional[str] = Field(
        alias="wallet_key_derivation", default=None
    )
    wallet_name: Optional[str] = Field(alias="wallet_name", default=None)
    wallet_type: Optional[str] = Field(alias="wallet_type", default=None)
    wallet_webhook_urls: Optional[List[str]] = Field(
        alias="wallet_webhook_urls", default=None
    )


CreateWalletRequest.update_forward_refs()
