# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.credential_definition_value import (
    CredentialDefinitionValue,
)


class CredentialDefinition(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CredentialDefinition - a model defined in OpenAPI

        id: The id of this CredentialDefinition [Optional].
        schema_id: The schema_id of this CredentialDefinition [Optional].
        tag: The tag of this CredentialDefinition [Optional].
        type: The type of this CredentialDefinition [Optional].
        value: The value of this CredentialDefinition [Optional].
        ver: The ver of this CredentialDefinition [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    schema_id: Optional[str] = Field(alias="schemaId", default=None)
    tag: Optional[str] = Field(alias="tag", default=None)
    type: Optional[Dict[str, Any]] = Field(alias="type", default=None)
    value: Optional[CredentialDefinitionValue] = Field(alias="value", default=None)
    ver: Optional[str] = Field(alias="ver", default=None)

    @validator("id")
    def id_pattern(cls, value):
        assert value is not None and re.match(
            r"^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):3:CL:(([1-9][0-9]*)|([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}:2:.+:[0-9.]+)):(.+)?$",
            value,
        )
        return value

    @validator("ver")
    def ver_pattern(cls, value):
        assert value is not None and re.match(r"^[0-9.]+$", value)
        return value


CredentialDefinition.update_forward_refs()
