# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.cred_def_value import CredDefValue
from acapy_wrapper_074.models.cred_def_value_primary import CredDefValuePrimary
from acapy_wrapper_074.models.cred_def_value_revocation import CredDefValueRevocation


class CredentialDefinitionValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CredentialDefinitionValue - a model defined in OpenAPI

        primary: The primary of this CredentialDefinitionValue [Optional].
        revocation: The revocation of this CredentialDefinitionValue [Optional].
    """

    primary: Optional[CredDefValuePrimary] = Field(alias="primary", default=None)
    revocation: Optional[CredDefValueRevocation] = Field(
        alias="revocation", default=None
    )


CredentialDefinitionValue.update_forward_refs()
