# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.cred_attr_spec import CredAttrSpec


class CredentialPreview(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CredentialPreview - a model defined in OpenAPI

        type: The type of this CredentialPreview [Optional].
        attributes: The attributes of this CredentialPreview.
    """

    type: Optional[str] = Field(alias="@type", default=None)
    attributes: List[CredAttrSpec] = Field(alias="attributes")


CredentialPreview.update_forward_refs()
