# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DIDCreateOptions(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIDCreateOptions - a model defined in OpenAPI

        key_type: The key_type of this DIDCreateOptions.
    """

    key_type: str = Field(alias="key_type")


DIDCreateOptions.update_forward_refs()
