# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.filter import Filter


class DIFField(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFField - a model defined in OpenAPI

        filter: The filter of this DIFField [Optional].
        id: The id of this DIFField [Optional].
        path: The path of this DIFField [Optional].
        predicate: The predicate of this DIFField [Optional].
        purpose: The purpose of this DIFField [Optional].
    """

    filter: Optional[Filter] = Field(alias="filter", default=None)
    id: Optional[str] = Field(alias="id", default=None)
    path: Optional[List[str]] = Field(alias="path", default=None)
    predicate: Optional[str] = Field(alias="predicate", default=None)
    purpose: Optional[str] = Field(alias="purpose", default=None)


DIFField.update_forward_refs()
