# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.dif_options import DIFOptions
from acapy_wrapper_074.models.presentation_definition import PresentationDefinition


class DIFProofRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFProofRequest - a model defined in OpenAPI

        options: The options of this DIFProofRequest [Optional].
        presentation_definition: The presentation_definition of this DIFProofRequest.
    """

    options: Optional[DIFOptions] = Field(alias="options", default=None)
    presentation_definition: PresentationDefinition = Field(
        alias="presentation_definition"
    )


DIFProofRequest.update_forward_refs()
