# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DIFOptions(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DIFOptions - a model defined in OpenAPI

        challenge: The challenge of this DIFOptions [Optional].
        domain: The domain of this DIFOptions [Optional].
    """

    challenge: Optional[str] = Field(alias="challenge", default=None)
    domain: Optional[str] = Field(alias="domain", default=None)


DIFOptions.update_forward_refs()
