# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.indy_non_revoc_proof import IndyNonRevocProof


class IndyProofProofProofsProofNonRevocProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofProofProofsProofNonRevocProof - a model defined in OpenAPI

        c_list: The c_list of this IndyProofProofProofsProofNonRevocProof [Optional].
        x_list: The x_list of this IndyProofProofProofsProofNonRevocProof [Optional].
    """

    c_list: Optional[Dict[str, str]] = Field(alias="c_list", default=None)
    x_list: Optional[Dict[str, str]] = Field(alias="x_list", default=None)


IndyProofProofProofsProofNonRevocProof.update_forward_refs()
