# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.indy_proof_proof_proofs_proof_non_revoc_proof import (
    IndyProofProofProofsProofNonRevocProof,
)
from acapy_wrapper_074.models.indy_proof_proof_proofs_proof_primary_proof import (
    IndyProofProofProofsProofPrimaryProof,
)


class IndyProofProofProofsProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyProofProofProofsProof - a model defined in OpenAPI

        non_revoc_proof: The non_revoc_proof of this IndyProofProofProofsProof [Optional].
        primary_proof: The primary_proof of this IndyProofProofProofsProof [Optional].
    """

    non_revoc_proof: Optional[IndyProofProofProofsProofNonRevocProof] = Field(
        alias="non_revoc_proof", default=None
    )
    primary_proof: Optional[IndyProofProofProofsProofPrimaryProof] = Field(
        alias="primary_proof", default=None
    )


IndyProofProofProofsProof.update_forward_refs()
