# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.indy_cred_precis_cred_info import IndyCredPrecisCredInfo
from acapy_wrapper_074.models.indy_cred_precis_interval import IndyCredPrecisInterval


class IndyCredPrecis(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IndyCredPrecis - a model defined in OpenAPI

        cred_info: The cred_info of this IndyCredPrecis [Optional].
        interval: The interval of this IndyCredPrecis [Optional].
        presentation_referents: The presentation_referents of this IndyCredPrecis [Optional].
    """

    cred_info: Optional[IndyCredPrecisCredInfo] = Field(alias="cred_info", default=None)
    interval: Optional[IndyCredPrecisInterval] = Field(alias="interval", default=None)
    presentation_referents: Optional[List[str]] = Field(
        alias="presentation_referents", default=None
    )


IndyCredPrecis.update_forward_refs()
