# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.invitation_record_invitation import (
    InvitationRecordInvitation,
)


class InvitationRecord(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InvitationRecord - a model defined in OpenAPI

        created_at: The created_at of this InvitationRecord [Optional].
        invi_msg_id: The invi_msg_id of this InvitationRecord [Optional].
        invitation: The invitation of this InvitationRecord [Optional].
        invitation_id: The invitation_id of this InvitationRecord [Optional].
        invitation_url: The invitation_url of this InvitationRecord [Optional].
        oob_id: The oob_id of this InvitationRecord [Optional].
        state: The state of this InvitationRecord [Optional].
        trace: The trace of this InvitationRecord [Optional].
        updated_at: The updated_at of this InvitationRecord [Optional].
    """

    created_at: Optional[str] = Field(alias="created_at", default=None)
    invi_msg_id: Optional[str] = Field(alias="invi_msg_id", default=None)
    invitation: Optional[InvitationRecordInvitation] = Field(
        alias="invitation", default=None
    )
    invitation_id: Optional[str] = Field(alias="invitation_id", default=None)
    invitation_url: Optional[str] = Field(alias="invitation_url", default=None)
    oob_id: Optional[str] = Field(alias="oob_id", default=None)
    state: Optional[str] = Field(alias="state", default=None)
    trace: Optional[bool] = Field(alias="trace", default=None)
    updated_at: Optional[str] = Field(alias="updated_at", default=None)

    @validator("created_at")
    def created_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value

    @validator("updated_at")
    def updated_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value


InvitationRecord.update_forward_refs()
