# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class IssuerCredRevRecord(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IssuerCredRevRecord - a model defined in OpenAPI

        created_at: The created_at of this IssuerCredRevRecord [Optional].
        cred_def_id: The cred_def_id of this IssuerCredRevRecord [Optional].
        cred_ex_id: The cred_ex_id of this IssuerCredRevRecord [Optional].
        cred_rev_id: The cred_rev_id of this IssuerCredRevRecord [Optional].
        record_id: The record_id of this IssuerCredRevRecord [Optional].
        rev_reg_id: The rev_reg_id of this IssuerCredRevRecord [Optional].
        state: The state of this IssuerCredRevRecord [Optional].
        updated_at: The updated_at of this IssuerCredRevRecord [Optional].
    """

    created_at: Optional[str] = Field(alias="created_at", default=None)
    cred_def_id: Optional[str] = Field(alias="cred_def_id", default=None)
    cred_ex_id: Optional[str] = Field(alias="cred_ex_id", default=None)
    cred_rev_id: Optional[str] = Field(alias="cred_rev_id", default=None)
    record_id: Optional[str] = Field(alias="record_id", default=None)
    rev_reg_id: Optional[str] = Field(alias="rev_reg_id", default=None)
    state: Optional[str] = Field(alias="state", default=None)
    updated_at: Optional[str] = Field(alias="updated_at", default=None)

    @validator("created_at")
    def created_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value

    @validator("cred_def_id")
    def cred_def_id_pattern(cls, value):
        assert value is not None and re.match(
            r"^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):3:CL:(([1-9][0-9]*)|([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}:2:.+:[0-9.]+)):(.+)?$",
            value,
        )
        return value

    @validator("cred_rev_id")
    def cred_rev_id_pattern(cls, value):
        assert value is not None and re.match(r"^[1-9][0-9]*$", value)
        return value

    @validator("rev_reg_id")
    def rev_reg_id_pattern(cls, value):
        assert value is not None and re.match(
            r"^([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):4:([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}):3:CL:(([1-9][0-9]*)|([123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{21,22}:2:.+:[0-9.]+))(:.+)?:CL_ACCUM:(.+$)",
            value,
        )
        return value

    @validator("updated_at")
    def updated_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value


IssuerCredRevRecord.update_forward_refs()
