# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.keylist_query_paginate import KeylistQueryPaginate


class KeylistQuery(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    KeylistQuery - a model defined in OpenAPI

        id: The id of this KeylistQuery [Optional].
        type: The type of this KeylistQuery [Optional].
        filter: The filter of this KeylistQuery [Optional].
        paginate: The paginate of this KeylistQuery [Optional].
    """

    id: Optional[str] = Field(alias="@id", default=None)
    type: Optional[str] = Field(alias="@type", default=None)
    filter: Optional[Dict[str, Any]] = Field(alias="filter", default=None)
    paginate: Optional[KeylistQueryPaginate] = Field(alias="paginate", default=None)


KeylistQuery.update_forward_refs()
