# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.menu_form_param import MenuFormParam


class MenuForm(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MenuForm - a model defined in OpenAPI

        description: The description of this MenuForm [Optional].
        params: The params of this MenuForm [Optional].
        submit_label: The submit_label of this MenuForm [Optional].
        title: The title of this MenuForm [Optional].
    """

    description: Optional[str] = Field(alias="description", default=None)
    params: Optional[List[MenuFormParam]] = Field(alias="params", default=None)
    submit_label: Optional[str] = Field(alias="submit-label", default=None)
    title: Optional[str] = Field(alias="title", default=None)


MenuForm.update_forward_refs()
