# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class QueryItem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    QueryItem - a model defined in OpenAPI

        feature_type: The feature_type of this QueryItem.
        match: The match of this QueryItem.
    """

    feature_type: str = Field(alias="feature-type")
    match: str = Field(alias="match")


QueryItem.update_forward_refs()
