# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TAARecord(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TAARecord - a model defined in OpenAPI

        digest: The digest of this TAARecord [Optional].
        text: The text of this TAARecord [Optional].
        version: The version of this TAARecord [Optional].
    """

    digest: Optional[str] = Field(alias="digest", default=None)
    text: Optional[str] = Field(alias="text", default=None)
    version: Optional[str] = Field(alias="version", default=None)


TAARecord.update_forward_refs()
