# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.txn_or_register_ledger_nym_response_txn import (
    TxnOrRegisterLedgerNymResponseTxn,
)


class TxnOrRegisterLedgerNymResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TxnOrRegisterLedgerNymResponse - a model defined in OpenAPI

        success: The success of this TxnOrRegisterLedgerNymResponse [Optional].
        txn: The txn of this TxnOrRegisterLedgerNymResponse [Optional].
    """

    success: Optional[bool] = Field(alias="success", default=None)
    txn: Optional[TxnOrRegisterLedgerNymResponseTxn] = Field(alias="txn", default=None)


TxnOrRegisterLedgerNymResponse.update_forward_refs()
