# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.v10_presentation_exchange import V10PresentationExchange


class V10PresentationExchangeList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V10PresentationExchangeList - a model defined in OpenAPI

        results: The results of this V10PresentationExchangeList [Optional].
    """

    results: Optional[List[V10PresentationExchange]] = Field(
        alias="results", default=None
    )


V10PresentationExchangeList.update_forward_refs()
