# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.indy_pres_preview import IndyPresPreview


class V10PresentationProposalRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V10PresentationProposalRequest - a model defined in OpenAPI

        auto_present: The auto_present of this V10PresentationProposalRequest [Optional].
        comment: The comment of this V10PresentationProposalRequest [Optional].
        connection_id: The connection_id of this V10PresentationProposalRequest.
        presentation_proposal: The presentation_proposal of this V10PresentationProposalRequest.
        trace: The trace of this V10PresentationProposalRequest [Optional].
    """

    auto_present: Optional[bool] = Field(alias="auto_present", default=None)
    comment: Optional[str] = Field(alias="comment", default=None)
    connection_id: str = Field(alias="connection_id")
    presentation_proposal: IndyPresPreview = Field(alias="presentation_proposal")
    trace: Optional[bool] = Field(alias="trace", default=None)


V10PresentationProposalRequest.update_forward_refs()
