# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class V10PresentationSendRequestToProposal(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V10PresentationSendRequestToProposal - a model defined in OpenAPI

        auto_verify: The auto_verify of this V10PresentationSendRequestToProposal [Optional].
        trace: The trace of this V10PresentationSendRequestToProposal [Optional].
    """

    auto_verify: Optional[bool] = Field(alias="auto_verify", default=None)
    trace: Optional[bool] = Field(alias="trace", default=None)


V10PresentationSendRequestToProposal.update_forward_refs()
