# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.attach_decorator import AttachDecorator
from acapy_wrapper_074.models.v20_pres_format import V20PresFormat
from acapy_wrapper_074.models.v20_pres_request import V20PresRequest


class V20PresExRecordPresRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresExRecordPresRequest - a model defined in OpenAPI

        id: The id of this V20PresExRecordPresRequest [Optional].
        type: The type of this V20PresExRecordPresRequest [Optional].
        comment: The comment of this V20PresExRecordPresRequest [Optional].
        formats: The formats of this V20PresExRecordPresRequest.
        request_presentationsattach: The request_presentationsattach of this V20PresExRecordPresRequest.
        will_confirm: The will_confirm of this V20PresExRecordPresRequest [Optional].
    """

    id: Optional[str] = Field(alias="@id", default=None)
    type: Optional[str] = Field(alias="@type", default=None)
    comment: Optional[str] = Field(alias="comment", default=None)
    formats: List[V20PresFormat] = Field(alias="formats")
    request_presentationsattach: List[AttachDecorator] = Field(
        alias="request_presentations~attach"
    )
    will_confirm: Optional[bool] = Field(alias="will_confirm", default=None)


V20PresExRecordPresRequest.update_forward_refs()
