# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.indy_proof_req_attr_spec import IndyProofReqAttrSpec
from acapy_wrapper_074.models.indy_proof_req_pred_spec import IndyProofReqPredSpec
from acapy_wrapper_074.models.indy_proof_request import IndyProofRequest
from acapy_wrapper_074.models.indy_proof_request_non_revoked import (
    IndyProofRequestNonRevoked,
)


class V20PresProposalByFormatIndy(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresProposalByFormatIndy - a model defined in OpenAPI

        name: The name of this V20PresProposalByFormatIndy [Optional].
        non_revoked: The non_revoked of this V20PresProposalByFormatIndy [Optional].
        nonce: The nonce of this V20PresProposalByFormatIndy [Optional].
        requested_attributes: The requested_attributes of this V20PresProposalByFormatIndy.
        requested_predicates: The requested_predicates of this V20PresProposalByFormatIndy.
        version: The version of this V20PresProposalByFormatIndy [Optional].
    """

    name: Optional[str] = Field(alias="name", default=None)
    non_revoked: Optional[IndyProofRequestNonRevoked] = Field(
        alias="non_revoked", default=None
    )
    nonce: Optional[str] = Field(alias="nonce", default=None)
    requested_attributes: Dict[str, IndyProofReqAttrSpec] = Field(
        alias="requested_attributes"
    )
    requested_predicates: Dict[str, IndyProofReqPredSpec] = Field(
        alias="requested_predicates"
    )
    version: Optional[str] = Field(alias="version", default=None)

    @validator("nonce")
    def nonce_pattern(cls, value):
        assert value is not None and re.match(r"^[1-9][0-9]*$", value)
        return value

    @validator("version")
    def version_pattern(cls, value):
        assert value is not None and re.match(r"^[0-9.]+$", value)
        return value


V20PresProposalByFormatIndy.update_forward_refs()
