# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.v20_cred_filter import V20CredFilter
from acapy_wrapper_074.models.v20_cred_filter_indy import V20CredFilterIndy
from acapy_wrapper_074.models.v20_cred_filter_ld_proof import V20CredFilterLdProof


class V20CredBoundOfferRequestFilter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredBoundOfferRequestFilter - a model defined in OpenAPI

        indy: The indy of this V20CredBoundOfferRequestFilter [Optional].
        ld_proof: The ld_proof of this V20CredBoundOfferRequestFilter [Optional].
    """

    indy: Optional[V20CredFilterIndy] = Field(alias="indy", default=None)
    ld_proof: Optional[V20CredFilterLdProof] = Field(alias="ld_proof", default=None)


V20CredBoundOfferRequestFilter.update_forward_refs()
