# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.dif_pres_spec import DIFPresSpec
from acapy_wrapper_074.models.presentation_definition import PresentationDefinition


class V20PresSpecByFormatRequestDif(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20PresSpecByFormatRequestDif - a model defined in OpenAPI

        issuer_id: The issuer_id of this V20PresSpecByFormatRequestDif [Optional].
        presentation_definition: The presentation_definition of this V20PresSpecByFormatRequestDif [Optional].
        record_ids: The record_ids of this V20PresSpecByFormatRequestDif [Optional].
        reveal_doc: The reveal_doc of this V20PresSpecByFormatRequestDif [Optional].
    """

    issuer_id: Optional[str] = Field(alias="issuer_id", default=None)
    presentation_definition: Optional[PresentationDefinition] = Field(
        alias="presentation_definition", default=None
    )
    record_ids: Optional[Dict[str, Any]] = Field(alias="record_ids", default=None)
    reveal_doc: Optional[Dict[str, Any]] = Field(alias="reveal_doc", default=None)


V20PresSpecByFormatRequestDif.update_forward_refs()
