# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.v20_discovery_record_disclosures import (
    V20DiscoveryRecordDisclosures,
)
from acapy_wrapper_074.models.v20_discovery_record_queries_msg import (
    V20DiscoveryRecordQueriesMsg,
)


class V20DiscoveryRecord(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20DiscoveryRecord - a model defined in OpenAPI

        connection_id: The connection_id of this V20DiscoveryRecord [Optional].
        created_at: The created_at of this V20DiscoveryRecord [Optional].
        disclosures: The disclosures of this V20DiscoveryRecord [Optional].
        discovery_exchange_id: The discovery_exchange_id of this V20DiscoveryRecord [Optional].
        queries_msg: The queries_msg of this V20DiscoveryRecord [Optional].
        state: The state of this V20DiscoveryRecord [Optional].
        thread_id: The thread_id of this V20DiscoveryRecord [Optional].
        trace: The trace of this V20DiscoveryRecord [Optional].
        updated_at: The updated_at of this V20DiscoveryRecord [Optional].
    """

    connection_id: Optional[str] = Field(alias="connection_id", default=None)
    created_at: Optional[str] = Field(alias="created_at", default=None)
    disclosures: Optional[V20DiscoveryRecordDisclosures] = Field(
        alias="disclosures", default=None
    )
    discovery_exchange_id: Optional[str] = Field(
        alias="discovery_exchange_id", default=None
    )
    queries_msg: Optional[V20DiscoveryRecordQueriesMsg] = Field(
        alias="queries_msg", default=None
    )
    state: Optional[str] = Field(alias="state", default=None)
    thread_id: Optional[str] = Field(alias="thread_id", default=None)
    trace: Optional[bool] = Field(alias="trace", default=None)
    updated_at: Optional[str] = Field(alias="updated_at", default=None)

    @validator("created_at")
    def created_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value

    @validator("updated_at")
    def updated_at_pattern(cls, value):
        assert value is not None and re.match(
            r"^\d{4}-\d\d-\d\d[T ]\d\d:\d\d(?:\:(?:\d\d(?:\.\d{1,6})?))?(?:[+-]\d\d:?\d\d|Z|)$",
            value,
        )
        return value


V20DiscoveryRecord.update_forward_refs()
