# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.v20_cred_bound_offer_request_counter_preview import (
    V20CredBoundOfferRequestCounterPreview,
)
from acapy_wrapper_074.models.v20_cred_bound_offer_request_filter import (
    V20CredBoundOfferRequestFilter,
)


class V20CredBoundOfferRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredBoundOfferRequest - a model defined in OpenAPI

        counter_preview: The counter_preview of this V20CredBoundOfferRequest [Optional].
        filter: The filter of this V20CredBoundOfferRequest [Optional].
    """

    counter_preview: Optional[V20CredBoundOfferRequestCounterPreview] = Field(
        alias="counter_preview", default=None
    )
    filter: Optional[V20CredBoundOfferRequestFilter] = Field(
        alias="filter", default=None
    )


V20CredBoundOfferRequest.update_forward_refs()
