# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.ld_proof_vc_detail import LDProofVCDetail
from acapy_wrapper_074.models.ld_proof_vc_detail_credential import (
    LDProofVCDetailCredential,
)
from acapy_wrapper_074.models.ld_proof_vc_detail_options import LDProofVCDetailOptions


class V20CredFilterLdProof(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredFilterLdProof - a model defined in OpenAPI

        credential: The credential of this V20CredFilterLdProof.
        options: The options of this V20CredFilterLdProof.
    """

    credential: LDProofVCDetailCredential = Field(alias="credential")
    options: LDProofVCDetailOptions = Field(alias="options")


V20CredFilterLdProof.update_forward_refs()
