# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from acapy_wrapper_074.models.attach_decorator import AttachDecorator
from acapy_wrapper_074.models.v20_cred_format import V20CredFormat
from acapy_wrapper_074.models.v20_cred_offer import V20CredOffer
from acapy_wrapper_074.models.v20_cred_preview import V20CredPreview


class V20CredExRecordCredOffer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    V20CredExRecordCredOffer - a model defined in OpenAPI

        id: The id of this V20CredExRecordCredOffer [Optional].
        type: The type of this V20CredExRecordCredOffer [Optional].
        comment: The comment of this V20CredExRecordCredOffer [Optional].
        credential_preview: The credential_preview of this V20CredExRecordCredOffer [Optional].
        formats: The formats of this V20CredExRecordCredOffer.
        offersattach: The offersattach of this V20CredExRecordCredOffer.
        replacement_id: The replacement_id of this V20CredExRecordCredOffer [Optional].
    """

    id: Optional[str] = Field(alias="@id", default=None)
    type: Optional[str] = Field(alias="@type", default=None)
    comment: Optional[str] = Field(alias="comment", default=None)
    credential_preview: Optional[V20CredPreview] = Field(
        alias="credential_preview", default=None
    )
    formats: List[V20CredFormat] = Field(alias="formats")
    offersattach: List[AttachDecorator] = Field(alias="offers~attach")
    replacement_id: Optional[str] = Field(alias="replacement_id", default=None)


V20CredExRecordCredOffer.update_forward_refs()
