{{- if .Values.githubSecret.create -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "tekton.githubSecret" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tekton.githubSecret" . }}
  labels:
    {{ include "tekton.labels" . | nindent 4 }}  
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace }}
  {{- with .Values.githubSecret.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}  
type: Opaque
{{ if $secret -}}
# Secret found, write out existing token
data:
  secretToken: {{ $secret.data.secretToken }}
{{ else -}}
# Secret not found, generate new one...
data:
  secretToken: {{ randAlphaNum 32 | b64enc | quote }}
{{ end }}
{{- end }}