name: Uninstall PR instance
on:
  pull_request:
    branches:
      - main
    paths:
      - "plugins/**"
      - "services/tenant-ui/**"
      - "charts/traction/**"
      - "charts/tenant-ui/**"
    types:
      - closed

jobs:
  uninstall:
    name: Uninstall PR
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Check out manifest repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          path: charts-repo

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@5eb45e848b168b6bf6b8fe7f1561003c12e3c99d # v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Uninstall Traction via Helm
        continue-on-error: true
        run: |
          helm uninstall pr-${{ github.event.number }}-traction

      - name: Remove Traction Openshift Objects
        continue-on-error: true
        run: |
          oc delete secret,pvc --selector "app.kubernetes.io/instance"=pr-${{ github.event.number }}-traction

  clean-ghcr:
    runs-on: ubuntu-22.04
    if: ${{ always }}
    name: Delete closed PR images
    steps:
      - name: Delete Images
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: bcgov
          image-names: traction-plugins-acapy, traction-tenant-proxy, traction-tenant-ui
          image-tags: pr-${{ github.event.number }}
          cut-off: 1second
          token: ${{ secrets.GITHUB_TOKEN }}
